import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Errors logging platform",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-background h-screen flex items-center justify-center">
      {children}
    </main>
  );
}
