import { Sidebar } from "@/layout/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Errors logging platform",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex bg-[#171b2e]">
      <Sidebar />

      <div className="flex-1 h-screen bg-[#171b2e] overflow-y-scroll">
        {/* <Navbar /> */}

        <div className="sm:p-8 p-2 flex-1 mt-5 flex justify-center">
          <div className="flex-1 lg:max-w-[1300px] px-2 sm:px-4">
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}
